package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_jsonnet//jsonnet:jsonnet.bzl", "jsonnet_library")

jsonnet_library(
  name = "namespaces",
  srcs = ["namespaces.libsonnet"],
  visibility = ["//visibility:public"],
)


